global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'odoo'
    static_configs:
      - targets: ['odoo:8069']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
